version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:5000/health
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

